#!/usr/bin/env python
import pandas as pd
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
from geocoder.location import Location

import os
import sys
import time
import urllib.request

DEFAULT_REFRESH = 24 * 60 * 60

def print_msg(message, **kwargs):
    print(message, file=sys.stderr, **kwargs)

def refresh_data(url, filename, refresh_interval = DEFAULT_REFRESH):
    target_path = os.path.join(os.getcwd(), filename)
    last_modified = os.path.getmtime(target_path) if os.path.exists(target_path) else 0
    if refresh_interval < time.time() - last_modified:
        print_msg(f"Downloading from {url}...")
        urllib.request.urlretrieve(url, target_path)
        print_msg("done")
    else:
        print_msg(f"Using cached data at {target_path}")
    return target_path

def load_dataframe(url, filename, refresh_interval = DEFAULT_REFRESH):
    path = refresh_data(url, filename, refresh_interval)
    df = pd.read_csv(path, parse_dates=["starttime","endtime"], date_format="%I%p")
    return df

if __name__ == '__main__':
    df = load_dataframe("https://data.sfgov.org/api/views/jjew-r69b/rows.csv", "schedule.csv")
    epoch_t = time.time()
    t = time.localtime(epoch_t)
    midnight = int(time.mktime((t.tm_year, t.tm_mon, t.tm_mday, 0, 0, 0, 0, 0, -1)))
    nowtime = int(epoch_t- midnight)
    weekday = t.tm_wday
    print(df[df["DayOrder"] == weekday].head(5))

